# Generated by Django 2.1.4 on 2019-01-03 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvlizer', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BRUH', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(default='BRUH', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='endDate',
            field=models.CharField(default='BRUH', max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.CharField(default='BRUH', max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(default='BRUH', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='schoolLocation',
            field=models.CharField(default='BRUH', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='schoolName',
            field=models.CharField(default='BRUH', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='startDate',
            field=models.CharField(default='BRUH', max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='firstName',
            field=models.CharField(default='BRUH', max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='lastName',
            field=models.CharField(default='BRUH', max_length=255),
        ),
        migrations.AddField(
            model_name='education',
            name='Resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cvlizer.Resume'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='Resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cvlizer.Resume'),
        ),
    ]
