# Generated by Django 2.1.4 on 2019-01-04 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvlizer', '0003_auto_20190103_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=255)),
                ('jobTitle', models.CharField(max_length=255)),
                ('companyLocation', models.CharField(max_length=255)),
                ('startDate', models.CharField(max_length=50)),
                ('endDate', models.CharField(max_length=50)),
                ('jobResp', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='Resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cvlizer.Resume'),
        ),
    ]
