# Generated by Django 2.1.4 on 2019-01-04 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvlizer', '0004_auto_20190104_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=255)),
                ('projectDesc', models.TextField()),
                ('link', models.URLField()),
                ('tools', models.TextField()),
                ('Resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cvlizer.Resume')),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='Resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edus', to='cvlizer.Resume'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Resume',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinfo', to='cvlizer.Resume'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='Resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='cvlizer.Resume'),
        ),
    ]
