# Generated by Django 2.1.4 on 2019-01-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvlizer', '0005_auto_20190104_1344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
