# Generated by Django 2.1.4 on 2019-01-04 14:07

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('cvlizer', '0006_auto_20190104_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resume',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='Resume',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='Resume',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Resume',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='Resume',
            new_name='User',
        ),
    ]
