# Generated by Django 2.1.4 on 2019-01-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvlizer', '0008_auto_20190104_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillType', models.CharField(max_length=255)),
                ('skillList', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='endDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='schoolLocation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='schoolName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='startDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='firstName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='lastName',
            field=models.CharField(max_length=255),
        ),
    ]
