# Generated by Django 2.1.4 on 2019-01-08 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvlizer', '0009_auto_20190108_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cvlizer.User'),
        ),
    ]
