# Generated by Django 2.1.4 on 2019-01-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvlizer', '0010_skill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='relevantCourses',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
